apiVersion: v1
kind: Service
metadata:
  name: {{ template "core.fullname" . }}-bootnode
  labels:
    app: {{ template "core.name" . }}
    chart: {{ template "core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: bootnode
spec:
  selector:
    app: {{ template "core.name" . }}
    release: {{ .Release.Name }}
    component: bootnode
  clusterIP: None
  ports:
  - name: discovery
    port: 30330
    protocol: UDP
  - name: http
    port: 80
