kind: Service
apiVersion: v1
metadata:
  name: {{ template "core.fullname" . }}-gocore-tx
  labels:
    app: {{ template "core.name" . }}
    chart: {{ template "core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: gocore-tx
spec:
  selector:
    app: {{ template "core.name" . }}
    release: {{ .Release.Name }}
    component: gocore-tx
  type: {{ .Values.gocore.tx.service.type }}
  sessionAffinity: ClientIP
  ports:
  - name: rpc
    port: 8545
  - name: ws
    port: 8546
