apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "core.fullname" . }}-gocore-config
  labels:
    app: {{ template "core.name" . }}
    chart: {{ template "core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  networkid: "{{ .Values.gocore.genesis.networkId }}"
  genesis.json: |-
    {
        "config": {
            "chainId": {{ .Values.gocore.genesis.networkId }}
        },
        "difficulty":  {{ .Values.gocore.genesis.difficulty | quote }},
        "energyLimit": {{ .Values.gocore.genesis.energyLimit | quote }},
        "alloc": {
            {{- if .Values.gocore.account.address }}
            {{ .Values.gocore.account.address | quote }}: {
                "balance": "1000000000000000000000000"
            }
            {{- end }}
        }
    }
