apiVersion: v1
kind: Secret
metadata:
  name: {{ template "core.fullname" . }}-gocore-account
  labels:
    app: {{ template "core.name" . }}
    chart: {{ template "core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.gocore.account.privateKey }}
  accountPrivateKey: {{ .Values.gocore.account.privateKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.gocore.account.secret }}
  accountSecret: {{ .Values.gocore.account.secret | b64enc | quote }}
  {{- end }}
