apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "core.fullname" . }}-stats
  labels:
    app: {{ template "core.name" . }}
    chart: {{ template "core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "core.name" . }}
      release: {{ .Release.Name }}
      component: stats
  template:
    metadata:
      labels:
        app: {{ template "core.name" . }}
        release: {{ .Release.Name }}
        component: stats
    spec:
      containers:
      - name: stats
        image: {{ .Values.stats.image.repository }}:{{ .Values.stats.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: WS_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "core.fullname" . }}-stats
              key: WS_SECRET
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
