apiVersion: v1
kind: Secret
metadata:
  name: {{ template "core.fullname" . }}-stats
  labels:
    app: {{ template "core.name" . }}
    chart: {{ template "core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  WS_SECRET: {{ .Values.stats.webSocketSecret | b64enc | quote }}
