kind: Service
apiVersion: v1
metadata:
  name: {{ template "core.fullname" . }}-stats
  labels:
    app: {{ template "core.name" . }}
    chart: {{ template "core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: stats
spec:
  selector:
    app: {{ template "core.name" . }}
    release: {{ .Release.Name }}
    component: stats
  type: {{ .Values.stats.service.type }}
  ports:
  - port: 80
    targetPort: http
